// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kript/api/data.proto

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// A permission that a user can have on a datum.
type Permission int32

const (
	Permission_UNKNOWN Permission = 0
	// Permission to read the datum.
	Permission_READ Permission = 1
	// Permission to read and write the datum.
	Permission_WRITE Permission = 2
	// Permission to read and delete the datum.
	Permission_DELETE Permission = 3
	// Permission to read and share the datum with other users. The user has the power
	// to share the same permissions that they have.
	Permission_SHARE Permission = 4
	// Full permission on the datum.
	Permission_ADMIN Permission = 5
)

var Permission_name = map[int32]string{
	0: "UNKNOWN",
	1: "READ",
	2: "WRITE",
	3: "DELETE",
	4: "SHARE",
	5: "ADMIN",
}

var Permission_value = map[string]int32{
	"UNKNOWN": 0,
	"READ":    1,
	"WRITE":   2,
	"DELETE":  3,
	"SHARE":   4,
	"ADMIN":   5,
}

func (x Permission) String() string {
	return proto.EnumName(Permission_name, int32(x))
}

func (Permission) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{0}
}

type Datum struct {
	// The identifier of this datum.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The owner of this datum.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// The title of this datum, given by the user.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// The actual data of this datum, such as a password or code, encrypted.
	// This should decrypt to a string of a json object.
	Data string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// The encryption algorithm used to encrypt the actual data.
	DataEncryptionAlgorithm SEncryptionAlgorithm `protobuf:"varint,5,opt,name=data_encryption_algorithm,json=dataEncryptionAlgorithm,proto3,enum=kript.api.SEncryptionAlgorithm" json:"data_encryption_algorithm,omitempty"`
	// A map of ids of users who have access to this datum to information on what
	// permissions they have. This does not include the owner, who has all permissions.
	Accessors map[string]*Datum_Access `protobuf:"bytes,6,rep,name=accessors,proto3" json:"accessors,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The metadata associated with this datum.
	Metadata             *Datum_Metadata `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Datum) Reset()         { *m = Datum{} }
func (m *Datum) String() string { return proto.CompactTextString(m) }
func (*Datum) ProtoMessage()    {}
func (*Datum) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{0}
}
func (m *Datum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Datum.Unmarshal(m, b)
}
func (m *Datum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Datum.Marshal(b, m, deterministic)
}
func (m *Datum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Datum.Merge(m, src)
}
func (m *Datum) XXX_Size() int {
	return xxx_messageInfo_Datum.Size(m)
}
func (m *Datum) XXX_DiscardUnknown() {
	xxx_messageInfo_Datum.DiscardUnknown(m)
}

var xxx_messageInfo_Datum proto.InternalMessageInfo

func (m *Datum) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Datum) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Datum) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Datum) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Datum) GetDataEncryptionAlgorithm() SEncryptionAlgorithm {
	if m != nil {
		return m.DataEncryptionAlgorithm
	}
	return SEncryptionAlgorithm_UNKNOWN_S_ENCRYPTION_ALGORITHM
}

func (m *Datum) GetAccessors() map[string]*Datum_Access {
	if m != nil {
		return m.Accessors
	}
	return nil
}

func (m *Datum) GetMetadata() *Datum_Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// An object representing relevant data to a user who has access to this
// datum.
type Datum_Access struct {
	// The id of the user whom this access object is associated with.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The key used to encrypt the actual data, encrypted using this user's
	// public key and decrypted with their private key.
	DataKey string `protobuf:"bytes,2,opt,name=data_key,json=dataKey,proto3" json:"data_key,omitempty"`
	// The list of permissions this user has on this datum.
	Permissions          []Permission `protobuf:"varint,3,rep,packed,name=permissions,proto3,enum=kript.api.Permission" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Datum_Access) Reset()         { *m = Datum_Access{} }
func (m *Datum_Access) String() string { return proto.CompactTextString(m) }
func (*Datum_Access) ProtoMessage()    {}
func (*Datum_Access) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{0, 1}
}
func (m *Datum_Access) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Datum_Access.Unmarshal(m, b)
}
func (m *Datum_Access) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Datum_Access.Marshal(b, m, deterministic)
}
func (m *Datum_Access) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Datum_Access.Merge(m, src)
}
func (m *Datum_Access) XXX_Size() int {
	return xxx_messageInfo_Datum_Access.Size(m)
}
func (m *Datum_Access) XXX_DiscardUnknown() {
	xxx_messageInfo_Datum_Access.DiscardUnknown(m)
}

var xxx_messageInfo_Datum_Access proto.InternalMessageInfo

func (m *Datum_Access) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Datum_Access) GetDataKey() string {
	if m != nil {
		return m.DataKey
	}
	return ""
}

func (m *Datum_Access) GetPermissions() []Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

// The metadata associated with this datum.
type Datum_Metadata struct {
	// The user who created and owns this datum.
	OwnerId string `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// The time at which this datum was created.
	CreatedTime *types.Timestamp `protobuf:"bytes,2,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// The time at which this datum was last modified.
	LastEdited *types.Timestamp `protobuf:"bytes,3,opt,name=last_edited,json=lastEdited,proto3" json:"last_edited,omitempty"`
	// A map of id of users with access or who once had access to metadata
	// associated with that access.
	AccessMetadata       map[string]*Datum_Metadata_AccessMetadata `protobuf:"bytes,4,rep,name=access_metadata,json=accessMetadata,proto3" json:"access_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *Datum_Metadata) Reset()         { *m = Datum_Metadata{} }
func (m *Datum_Metadata) String() string { return proto.CompactTextString(m) }
func (*Datum_Metadata) ProtoMessage()    {}
func (*Datum_Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{0, 2}
}
func (m *Datum_Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Datum_Metadata.Unmarshal(m, b)
}
func (m *Datum_Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Datum_Metadata.Marshal(b, m, deterministic)
}
func (m *Datum_Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Datum_Metadata.Merge(m, src)
}
func (m *Datum_Metadata) XXX_Size() int {
	return xxx_messageInfo_Datum_Metadata.Size(m)
}
func (m *Datum_Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Datum_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Datum_Metadata proto.InternalMessageInfo

func (m *Datum_Metadata) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Datum_Metadata) GetCreatedTime() *types.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *Datum_Metadata) GetLastEdited() *types.Timestamp {
	if m != nil {
		return m.LastEdited
	}
	return nil
}

func (m *Datum_Metadata) GetAccessMetadata() map[string]*Datum_Metadata_AccessMetadata {
	if m != nil {
		return m.AccessMetadata
	}
	return nil
}

// Metadata associated with a user who had access to this datum at some
// point.
type Datum_Metadata_AccessMetadata struct {
	// The grants and revokes that have been given to the user.
	GrantMetadata        []*Datum_Metadata_AccessMetadata_PermissionGrantMetadata `protobuf:"bytes,1,rep,name=grant_metadata,json=grantMetadata,proto3" json:"grant_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                 `json:"-"`
	XXX_unrecognized     []byte                                                   `json:"-"`
	XXX_sizecache        int32                                                    `json:"-"`
}

func (m *Datum_Metadata_AccessMetadata) Reset()         { *m = Datum_Metadata_AccessMetadata{} }
func (m *Datum_Metadata_AccessMetadata) String() string { return proto.CompactTextString(m) }
func (*Datum_Metadata_AccessMetadata) ProtoMessage()    {}
func (*Datum_Metadata_AccessMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{0, 2, 1}
}
func (m *Datum_Metadata_AccessMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Datum_Metadata_AccessMetadata.Unmarshal(m, b)
}
func (m *Datum_Metadata_AccessMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Datum_Metadata_AccessMetadata.Marshal(b, m, deterministic)
}
func (m *Datum_Metadata_AccessMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Datum_Metadata_AccessMetadata.Merge(m, src)
}
func (m *Datum_Metadata_AccessMetadata) XXX_Size() int {
	return xxx_messageInfo_Datum_Metadata_AccessMetadata.Size(m)
}
func (m *Datum_Metadata_AccessMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Datum_Metadata_AccessMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_Datum_Metadata_AccessMetadata proto.InternalMessageInfo

func (m *Datum_Metadata_AccessMetadata) GetGrantMetadata() []*Datum_Metadata_AccessMetadata_PermissionGrantMetadata {
	if m != nil {
		return m.GrantMetadata
	}
	return nil
}

// Metadata associated with a change in access permissions.
type Datum_Metadata_AccessMetadata_PermissionGrantMetadata struct {
	// The id of the user who granted or revoked a permission.
	GranterId string `protobuf:"bytes,1,opt,name=granter_id,json=granterId,proto3" json:"granter_id,omitempty"`
	// The permission that was granted or revoked.
	Permission Permission `protobuf:"varint,2,opt,name=permission,proto3,enum=kript.api.Permission" json:"permission,omitempty"`
	// If true, this grant was a grant. Otherwise, it was a revoke.
	IsGrant              bool     `protobuf:"varint,3,opt,name=is_grant,json=isGrant,proto3" json:"is_grant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Datum_Metadata_AccessMetadata_PermissionGrantMetadata) Reset() {
	*m = Datum_Metadata_AccessMetadata_PermissionGrantMetadata{}
}
func (m *Datum_Metadata_AccessMetadata_PermissionGrantMetadata) String() string {
	return proto.CompactTextString(m)
}
func (*Datum_Metadata_AccessMetadata_PermissionGrantMetadata) ProtoMessage() {}
func (*Datum_Metadata_AccessMetadata_PermissionGrantMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{0, 2, 1, 0}
}
func (m *Datum_Metadata_AccessMetadata_PermissionGrantMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Datum_Metadata_AccessMetadata_PermissionGrantMetadata.Unmarshal(m, b)
}
func (m *Datum_Metadata_AccessMetadata_PermissionGrantMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Datum_Metadata_AccessMetadata_PermissionGrantMetadata.Marshal(b, m, deterministic)
}
func (m *Datum_Metadata_AccessMetadata_PermissionGrantMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Datum_Metadata_AccessMetadata_PermissionGrantMetadata.Merge(m, src)
}
func (m *Datum_Metadata_AccessMetadata_PermissionGrantMetadata) XXX_Size() int {
	return xxx_messageInfo_Datum_Metadata_AccessMetadata_PermissionGrantMetadata.Size(m)
}
func (m *Datum_Metadata_AccessMetadata_PermissionGrantMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Datum_Metadata_AccessMetadata_PermissionGrantMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_Datum_Metadata_AccessMetadata_PermissionGrantMetadata proto.InternalMessageInfo

func (m *Datum_Metadata_AccessMetadata_PermissionGrantMetadata) GetGranterId() string {
	if m != nil {
		return m.GranterId
	}
	return ""
}

func (m *Datum_Metadata_AccessMetadata_PermissionGrantMetadata) GetPermission() Permission {
	if m != nil {
		return m.Permission
	}
	return Permission_UNKNOWN
}

func (m *Datum_Metadata_AccessMetadata_PermissionGrantMetadata) GetIsGrant() bool {
	if m != nil {
		return m.IsGrant
	}
	return false
}

type GetDataRequest struct {
	// The access token to identify and authenticate the user.
	AccessToken *AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// The list of ids of datums to retrieve. If empty, all datums that the user
	// has access to will be retrieved.
	DatumIds             []string `protobuf:"bytes,2,rep,name=datum_ids,json=datumIds,proto3" json:"datum_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataRequest) Reset()         { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()    {}
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{1}
}
func (m *GetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRequest.Unmarshal(m, b)
}
func (m *GetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRequest.Marshal(b, m, deterministic)
}
func (m *GetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRequest.Merge(m, src)
}
func (m *GetDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataRequest.Size(m)
}
func (m *GetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRequest proto.InternalMessageInfo

func (m *GetDataRequest) GetAccessToken() *AccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

func (m *GetDataRequest) GetDatumIds() []string {
	if m != nil {
		return m.DatumIds
	}
	return nil
}

type GetDataResponse struct {
	// The datums requested by the user.
	Datums               []*Datum `protobuf:"bytes,1,rep,name=datums,proto3" json:"datums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataResponse) Reset()         { *m = GetDataResponse{} }
func (m *GetDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataResponse) ProtoMessage()    {}
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{2}
}
func (m *GetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponse.Unmarshal(m, b)
}
func (m *GetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponse.Marshal(b, m, deterministic)
}
func (m *GetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponse.Merge(m, src)
}
func (m *GetDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataResponse.Size(m)
}
func (m *GetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponse proto.InternalMessageInfo

func (m *GetDataResponse) GetDatums() []*Datum {
	if m != nil {
		return m.Datums
	}
	return nil
}

type UpdateDatumRequest struct {
	// The access token to identify and authenticate the user.
	AccessToken *AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// The id of the datum to update.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The new title of the. (Optional)
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// The new actual data of the datum, such as a password or code, encrypted.
	// This should decrypt to a string of a json object. (Optional)
	Data                 string   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDatumRequest) Reset()         { *m = UpdateDatumRequest{} }
func (m *UpdateDatumRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDatumRequest) ProtoMessage()    {}
func (*UpdateDatumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{3}
}
func (m *UpdateDatumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDatumRequest.Unmarshal(m, b)
}
func (m *UpdateDatumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDatumRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDatumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDatumRequest.Merge(m, src)
}
func (m *UpdateDatumRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDatumRequest.Size(m)
}
func (m *UpdateDatumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDatumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDatumRequest proto.InternalMessageInfo

func (m *UpdateDatumRequest) GetAccessToken() *AccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

func (m *UpdateDatumRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateDatumRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateDatumRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type UpdateDatumResponse struct {
	// The updated datum.
	Datum                *Datum   `protobuf:"bytes,1,opt,name=datum,proto3" json:"datum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDatumResponse) Reset()         { *m = UpdateDatumResponse{} }
func (m *UpdateDatumResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDatumResponse) ProtoMessage()    {}
func (*UpdateDatumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{4}
}
func (m *UpdateDatumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDatumResponse.Unmarshal(m, b)
}
func (m *UpdateDatumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDatumResponse.Marshal(b, m, deterministic)
}
func (m *UpdateDatumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDatumResponse.Merge(m, src)
}
func (m *UpdateDatumResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDatumResponse.Size(m)
}
func (m *UpdateDatumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDatumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDatumResponse proto.InternalMessageInfo

func (m *UpdateDatumResponse) GetDatum() *Datum {
	if m != nil {
		return m.Datum
	}
	return nil
}

type CreateDatumRequest struct {
	// The access token to identify and authenticate the user.
	AccessToken *AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// The title of the datum. (Optional)
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// The actual data of the datum, such as a password or code, encrypted.
	// This should decrypt to a string of a json object.
	Data string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// The key used to encrypt the actual data, encrypted using the owner's
	// public key and decrypted with their private key.
	DataKey string `protobuf:"bytes,5,opt,name=data_key,json=dataKey,proto3" json:"data_key,omitempty"`
	// The encryption algorithm used to encrypt the actual data.
	DataEncryptionAlgorithm SEncryptionAlgorithm `protobuf:"varint,6,opt,name=data_encryption_algorithm,json=dataEncryptionAlgorithm,proto3,enum=kript.api.SEncryptionAlgorithm" json:"data_encryption_algorithm,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}             `json:"-"`
	XXX_unrecognized        []byte               `json:"-"`
	XXX_sizecache           int32                `json:"-"`
}

func (m *CreateDatumRequest) Reset()         { *m = CreateDatumRequest{} }
func (m *CreateDatumRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDatumRequest) ProtoMessage()    {}
func (*CreateDatumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{5}
}
func (m *CreateDatumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDatumRequest.Unmarshal(m, b)
}
func (m *CreateDatumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDatumRequest.Marshal(b, m, deterministic)
}
func (m *CreateDatumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDatumRequest.Merge(m, src)
}
func (m *CreateDatumRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDatumRequest.Size(m)
}
func (m *CreateDatumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDatumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDatumRequest proto.InternalMessageInfo

func (m *CreateDatumRequest) GetAccessToken() *AccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

func (m *CreateDatumRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateDatumRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *CreateDatumRequest) GetDataKey() string {
	if m != nil {
		return m.DataKey
	}
	return ""
}

func (m *CreateDatumRequest) GetDataEncryptionAlgorithm() SEncryptionAlgorithm {
	if m != nil {
		return m.DataEncryptionAlgorithm
	}
	return SEncryptionAlgorithm_UNKNOWN_S_ENCRYPTION_ALGORITHM
}

type CreateDatumResponse struct {
	// The created datum.
	Datum                *Datum   `protobuf:"bytes,1,opt,name=datum,proto3" json:"datum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDatumResponse) Reset()         { *m = CreateDatumResponse{} }
func (m *CreateDatumResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDatumResponse) ProtoMessage()    {}
func (*CreateDatumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{6}
}
func (m *CreateDatumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDatumResponse.Unmarshal(m, b)
}
func (m *CreateDatumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDatumResponse.Marshal(b, m, deterministic)
}
func (m *CreateDatumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDatumResponse.Merge(m, src)
}
func (m *CreateDatumResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDatumResponse.Size(m)
}
func (m *CreateDatumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDatumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDatumResponse proto.InternalMessageInfo

func (m *CreateDatumResponse) GetDatum() *Datum {
	if m != nil {
		return m.Datum
	}
	return nil
}

type DeleteDatumRequest struct {
	// The access token to identify and authenticate the user.
	AccessToken *AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// The id of the datum to delete.
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDatumRequest) Reset()         { *m = DeleteDatumRequest{} }
func (m *DeleteDatumRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDatumRequest) ProtoMessage()    {}
func (*DeleteDatumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{7}
}
func (m *DeleteDatumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDatumRequest.Unmarshal(m, b)
}
func (m *DeleteDatumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDatumRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDatumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDatumRequest.Merge(m, src)
}
func (m *DeleteDatumRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDatumRequest.Size(m)
}
func (m *DeleteDatumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDatumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDatumRequest proto.InternalMessageInfo

func (m *DeleteDatumRequest) GetAccessToken() *AccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

func (m *DeleteDatumRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteDatumResponse struct {
	// The deleted datum, as it was before deletion.
	Datum                *Datum   `protobuf:"bytes,1,opt,name=datum,proto3" json:"datum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDatumResponse) Reset()         { *m = DeleteDatumResponse{} }
func (m *DeleteDatumResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDatumResponse) ProtoMessage()    {}
func (*DeleteDatumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{8}
}
func (m *DeleteDatumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDatumResponse.Unmarshal(m, b)
}
func (m *DeleteDatumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDatumResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDatumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDatumResponse.Merge(m, src)
}
func (m *DeleteDatumResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDatumResponse.Size(m)
}
func (m *DeleteDatumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDatumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDatumResponse proto.InternalMessageInfo

func (m *DeleteDatumResponse) GetDatum() *Datum {
	if m != nil {
		return m.Datum
	}
	return nil
}

type ShareDatumRequest struct {
	// The access token to identify and authenticate the user.
	AccessToken *AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// The id of the datum to share.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The id of the user the datum should be shared with.
	TargetId string `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// The key used to encrypt the actual data, encrypted using the target user's
	// public key and decrypted with their private key.
	DataKey string `protobuf:"bytes,4,opt,name=data_key,json=dataKey,proto3" json:"data_key,omitempty"`
	// The permissions to be granted to this user. These are in addition to any
	// permissions the user already has.
	Permissions          []Permission `protobuf:"varint,5,rep,packed,name=permissions,proto3,enum=kript.api.Permission" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ShareDatumRequest) Reset()         { *m = ShareDatumRequest{} }
func (m *ShareDatumRequest) String() string { return proto.CompactTextString(m) }
func (*ShareDatumRequest) ProtoMessage()    {}
func (*ShareDatumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{9}
}
func (m *ShareDatumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareDatumRequest.Unmarshal(m, b)
}
func (m *ShareDatumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareDatumRequest.Marshal(b, m, deterministic)
}
func (m *ShareDatumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareDatumRequest.Merge(m, src)
}
func (m *ShareDatumRequest) XXX_Size() int {
	return xxx_messageInfo_ShareDatumRequest.Size(m)
}
func (m *ShareDatumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareDatumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShareDatumRequest proto.InternalMessageInfo

func (m *ShareDatumRequest) GetAccessToken() *AccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

func (m *ShareDatumRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ShareDatumRequest) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *ShareDatumRequest) GetDataKey() string {
	if m != nil {
		return m.DataKey
	}
	return ""
}

func (m *ShareDatumRequest) GetPermissions() []Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type ShareDatumResponse struct {
	// The shared datum.
	Datum                *Datum   `protobuf:"bytes,1,opt,name=datum,proto3" json:"datum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareDatumResponse) Reset()         { *m = ShareDatumResponse{} }
func (m *ShareDatumResponse) String() string { return proto.CompactTextString(m) }
func (*ShareDatumResponse) ProtoMessage()    {}
func (*ShareDatumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e2363775050acee, []int{10}
}
func (m *ShareDatumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareDatumResponse.Unmarshal(m, b)
}
func (m *ShareDatumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareDatumResponse.Marshal(b, m, deterministic)
}
func (m *ShareDatumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareDatumResponse.Merge(m, src)
}
func (m *ShareDatumResponse) XXX_Size() int {
	return xxx_messageInfo_ShareDatumResponse.Size(m)
}
func (m *ShareDatumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareDatumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShareDatumResponse proto.InternalMessageInfo

func (m *ShareDatumResponse) GetDatum() *Datum {
	if m != nil {
		return m.Datum
	}
	return nil
}

func init() {
	proto.RegisterEnum("kript.api.Permission", Permission_name, Permission_value)
	proto.RegisterType((*Datum)(nil), "kript.api.Datum")
	proto.RegisterMapType((map[string]*Datum_Access)(nil), "kript.api.Datum.AccessorsEntry")
	proto.RegisterType((*Datum_Access)(nil), "kript.api.Datum.Access")
	proto.RegisterType((*Datum_Metadata)(nil), "kript.api.Datum.Metadata")
	proto.RegisterMapType((map[string]*Datum_Metadata_AccessMetadata)(nil), "kript.api.Datum.Metadata.AccessMetadataEntry")
	proto.RegisterType((*Datum_Metadata_AccessMetadata)(nil), "kript.api.Datum.Metadata.AccessMetadata")
	proto.RegisterType((*Datum_Metadata_AccessMetadata_PermissionGrantMetadata)(nil), "kript.api.Datum.Metadata.AccessMetadata.PermissionGrantMetadata")
	proto.RegisterType((*GetDataRequest)(nil), "kript.api.GetDataRequest")
	proto.RegisterType((*GetDataResponse)(nil), "kript.api.GetDataResponse")
	proto.RegisterType((*UpdateDatumRequest)(nil), "kript.api.UpdateDatumRequest")
	proto.RegisterType((*UpdateDatumResponse)(nil), "kript.api.UpdateDatumResponse")
	proto.RegisterType((*CreateDatumRequest)(nil), "kript.api.CreateDatumRequest")
	proto.RegisterType((*CreateDatumResponse)(nil), "kript.api.CreateDatumResponse")
	proto.RegisterType((*DeleteDatumRequest)(nil), "kript.api.DeleteDatumRequest")
	proto.RegisterType((*DeleteDatumResponse)(nil), "kript.api.DeleteDatumResponse")
	proto.RegisterType((*ShareDatumRequest)(nil), "kript.api.ShareDatumRequest")
	proto.RegisterType((*ShareDatumResponse)(nil), "kript.api.ShareDatumResponse")
}

func init() { proto.RegisterFile("kript/api/data.proto", fileDescriptor_7e2363775050acee) }

var fileDescriptor_7e2363775050acee = []byte{
	// 1072 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x8f, 0xdb, 0x44,
	0x14, 0xc7, 0x4e, 0x9c, 0x3f, 0xcf, 0x6d, 0x6a, 0xa6, 0xa5, 0x9b, 0x75, 0x5b, 0x1a, 0xf9, 0x80,
	0x42, 0xc4, 0xda, 0x90, 0xd5, 0x0a, 0xba, 0x65, 0x11, 0x81, 0x44, 0x25, 0x5a, 0xba, 0xad, 0xbc,
	0xbb, 0x54, 0xa2, 0x12, 0xd1, 0x6c, 0x3c, 0x38, 0x56, 0x12, 0xdb, 0x78, 0x26, 0x5b, 0xed, 0x95,
	0x03, 0x12, 0x1c, 0xe1, 0x83, 0x71, 0xe0, 0xce, 0x89, 0x13, 0x17, 0xc4, 0x37, 0x40, 0x33, 0x76,
	0x1c, 0x7b, 0x93, 0xac, 0xb2, 0x2a, 0x3d, 0xd9, 0xef, 0xbd, 0x9f, 0x7f, 0xef, 0xef, 0xbc, 0x31,
	0xdc, 0x19, 0x47, 0x5e, 0xc8, 0x2c, 0x1c, 0x7a, 0x96, 0x83, 0x19, 0x36, 0xc3, 0x28, 0x60, 0x01,
	0xaa, 0x0a, 0xad, 0x89, 0x43, 0x4f, 0xdf, 0x5e, 0x00, 0x66, 0xbe, 0x77, 0x4e, 0x22, 0x8a, 0x27,
	0x31, 0x4a, 0xbf, 0xef, 0x06, 0x81, 0x3b, 0x21, 0xc2, 0x86, 0x7d, 0x3f, 0x60, 0x98, 0x79, 0x81,
	0x4f, 0x13, 0xeb, 0xc3, 0xc4, 0x2a, 0xa4, 0xb3, 0xd9, 0xf7, 0x16, 0xf3, 0xa6, 0x84, 0x32, 0x3c,
	0x0d, 0x13, 0xc0, 0x07, 0xe2, 0x31, 0xdc, 0x71, 0x89, 0xbf, 0x43, 0x5f, 0x61, 0xd7, 0x25, 0x91,
	0x15, 0x84, 0x82, 0x62, 0x99, 0xce, 0xf8, 0xbb, 0x02, 0x4a, 0x17, 0xb3, 0xd9, 0x14, 0xd5, 0x40,
	0xf6, 0x9c, 0xba, 0xd4, 0x90, 0x9a, 0x55, 0x5b, 0xf6, 0x1c, 0x74, 0x07, 0x94, 0xe0, 0x95, 0x4f,
	0xa2, 0xba, 0x2c, 0x54, 0xb1, 0xc0, 0xb5, 0xcc, 0x63, 0x13, 0x52, 0x2f, 0xc4, 0x5a, 0x21, 0x20,
	0x04, 0x45, 0x9e, 0x66, 0xbd, 0x28, 0x94, 0xe2, 0x1d, 0xbd, 0x84, 0x6d, 0xfe, 0x1c, 0x10, 0x7f,
	0x18, 0x5d, 0x08, 0xff, 0x03, 0x3c, 0x71, 0x83, 0xc8, 0x63, 0xa3, 0x69, 0x5d, 0x69, 0x48, 0xcd,
	0x5a, 0xfb, 0xa1, 0x99, 0x16, 0xc4, 0x3c, 0xee, 0xa5, 0xb8, 0xce, 0x1c, 0x66, 0x6f, 0x71, 0x86,
	0x15, 0x06, 0x74, 0x00, 0x55, 0x3c, 0x1c, 0x12, 0x4a, 0x83, 0x88, 0xd6, 0x4b, 0x8d, 0x42, 0x53,
	0xcd, 0x91, 0x89, 0x8c, 0xcc, 0xce, 0x1c, 0xd1, 0xf3, 0x59, 0x74, 0x61, 0x2f, 0xbe, 0x40, 0x7b,
	0x50, 0x99, 0x12, 0x86, 0x45, 0xcc, 0xe5, 0x86, 0xd4, 0x54, 0xdb, 0xdb, 0x4b, 0x5f, 0x3f, 0x4d,
	0x00, 0x76, 0x0a, 0xd5, 0x4f, 0xa1, 0x96, 0xe7, 0x44, 0x1a, 0x14, 0xc6, 0xe4, 0x22, 0xa9, 0x1a,
	0x7f, 0x45, 0x3b, 0xa0, 0x9c, 0xe3, 0xc9, 0x8c, 0x88, 0xb2, 0xa9, 0xed, 0xad, 0x35, 0x51, 0xd9,
	0x31, 0x6a, 0x5f, 0xfe, 0x44, 0xd2, 0x67, 0x50, 0x8a, 0x95, 0x68, 0x0b, 0xca, 0x33, 0x4a, 0xa2,
	0x41, 0xda, 0x88, 0x12, 0x17, 0xfb, 0x0e, 0xda, 0x86, 0x8a, 0x28, 0x26, 0x77, 0x16, 0xf7, 0xa3,
	0xcc, 0xe5, 0x43, 0x72, 0x81, 0x3e, 0x06, 0x35, 0x24, 0xd1, 0xd4, 0xa3, 0x94, 0xb7, 0xb5, 0x5e,
	0x68, 0x14, 0x9a, 0xb5, 0xf6, 0x3b, 0x19, 0xb7, 0xcf, 0x53, 0xab, 0x9d, 0x45, 0xea, 0xff, 0x14,
	0xa1, 0x32, 0x4f, 0x92, 0x3b, 0x10, 0x0d, 0x5e, 0xb8, 0x2e, 0x0b, 0xb9, 0xef, 0xa0, 0x03, 0xb8,
	0x31, 0x8c, 0x08, 0x66, 0xc4, 0x19, 0xf0, 0x59, 0x4b, 0x12, 0xd3, 0xcd, 0x78, 0x10, 0xcd, 0xf9,
	0x20, 0x9a, 0x27, 0xf3, 0x41, 0xb4, 0xd5, 0x04, 0xcf, 0x35, 0xe8, 0x31, 0xa8, 0x13, 0x4c, 0xd9,
	0x80, 0x38, 0x1e, 0x23, 0x8e, 0x98, 0x9b, 0xab, 0xbf, 0x06, 0x0e, 0xef, 0x09, 0x34, 0xfa, 0x06,
	0x6e, 0xc5, 0x5d, 0x1b, 0xa4, 0xfd, 0x2a, 0x8a, 0x6e, 0xef, 0xac, 0xed, 0x57, 0x52, 0xe0, 0xb9,
	0x18, 0xf7, 0xbe, 0x86, 0x73, 0x4a, 0x7d, 0x0c, 0xb7, 0x57, 0xc0, 0x56, 0xb4, 0xf3, 0xb3, 0x7c,
	0x3b, 0x9b, 0x9b, 0xba, 0xcd, 0xf6, 0xf7, 0x27, 0x79, 0x3e, 0x37, 0x69, 0xb9, 0x5d, 0xa8, 0xb9,
	0x11, 0xf6, 0xd9, 0x22, 0x2d, 0x49, 0xa4, 0xf5, 0xf9, 0xa6, 0xfc, 0x99, 0xae, 0x3e, 0xe1, 0x44,
	0xa9, 0xdf, 0x9b, 0x6e, 0x56, 0xd4, 0x7f, 0x91, 0x60, 0x6b, 0x0d, 0x14, 0x3d, 0x00, 0x10, 0xe0,
	0x6c, 0xd7, 0xab, 0x89, 0xa6, 0xef, 0xa0, 0x3d, 0x80, 0xc5, 0xb8, 0x88, 0xfc, 0xd7, 0xce, 0x55,
	0x06, 0xc8, 0x27, 0xc9, 0xa3, 0x03, 0x41, 0x23, 0x9a, 0x5d, 0xb1, 0xcb, 0x1e, 0x15, 0x8e, 0x8d,
	0x11, 0xd4, 0x9e, 0x10, 0xd6, 0xe5, 0x61, 0x92, 0x1f, 0x66, 0x84, 0x32, 0xf4, 0x08, 0x6e, 0x24,
	0xfd, 0x65, 0xc1, 0x98, 0xf8, 0x22, 0x08, 0xb5, 0x7d, 0x37, 0xe3, 0x25, 0x4e, 0xfb, 0x84, 0x5b,
	0x6d, 0x15, 0x2f, 0x04, 0x74, 0x0f, 0xaa, 0x0e, 0xaf, 0xd0, 0xc0, 0x73, 0x68, 0x5d, 0x6e, 0x14,
	0x9a, 0x55, 0xbb, 0x22, 0x14, 0x7d, 0x87, 0x1a, 0x8f, 0xe1, 0x56, 0xea, 0x89, 0x86, 0x81, 0x4f,
	0x09, 0x6a, 0x42, 0x49, 0x98, 0x69, 0x52, 0x6a, 0xed, 0x72, 0xa9, 0xed, 0xc4, 0x6e, 0xfc, 0x2c,
	0x01, 0x3a, 0x0d, 0x1d, 0xcc, 0x48, 0xac, 0x7f, 0xfd, 0x58, 0xe3, 0xdd, 0x2a, 0x67, 0x77, 0xeb,
	0x66, 0x5b, 0xd4, 0x38, 0x80, 0xdb, 0xb9, 0x50, 0x92, 0x64, 0xde, 0x03, 0x45, 0x04, 0x9b, 0x04,
	0xb1, 0x9c, 0x4b, 0x6c, 0x36, 0xfe, 0x95, 0x00, 0x7d, 0x29, 0x0e, 0xe3, 0xff, 0x95, 0xca, 0xe6,
	0x17, 0x40, 0x76, 0x67, 0x29, 0xf9, 0x9d, 0x75, 0xe5, 0xdd, 0x50, 0x7a, 0xbd, 0xbb, 0x81, 0x97,
	0x2c, 0x97, 0xf2, 0x35, 0x4b, 0x36, 0x00, 0xd4, 0x25, 0x13, 0xf2, 0xc6, 0x9a, 0xcf, 0xe3, 0xcb,
	0x39, 0xb8, 0x66, 0x7c, 0xbf, 0x4b, 0xf0, 0xf6, 0xf1, 0x08, 0x47, 0x6f, 0x6c, 0x38, 0xef, 0x41,
	0x95, 0xe1, 0xc8, 0x25, 0x8c, 0x6f, 0x85, 0xb8, 0xcb, 0x95, 0x58, 0x71, 0xe9, 0x22, 0x2a, 0x5e,
	0x79, 0x11, 0x29, 0x9b, 0x5e, 0x44, 0xc6, 0xa7, 0x80, 0xb2, 0x09, 0x5d, 0xaf, 0x1e, 0xad, 0xe7,
	0x00, 0x0b, 0x62, 0xa4, 0x42, 0xf9, 0xf4, 0xe8, 0xf0, 0xe8, 0xd9, 0x8b, 0x23, 0xed, 0x2d, 0x54,
	0x81, 0xa2, 0xdd, 0xeb, 0x74, 0x35, 0x09, 0x55, 0x41, 0x79, 0x61, 0xf7, 0x4f, 0x7a, 0x9a, 0x8c,
	0x00, 0x4a, 0xdd, 0xde, 0xd7, 0xbd, 0x93, 0x9e, 0x56, 0xe0, 0xea, 0xe3, 0xaf, 0x3a, 0x76, 0x4f,
	0x2b, 0xf2, 0xd7, 0x4e, 0xf7, 0x69, 0xff, 0x48, 0x53, 0xda, 0x7f, 0x16, 0x40, 0xe5, 0xab, 0xe3,
	0x98, 0x44, 0xe7, 0xde, 0x90, 0xa0, 0x67, 0x50, 0x4e, 0x96, 0x09, 0xca, 0xfe, 0x26, 0xe4, 0x57,
	0x99, 0xae, 0xaf, 0x32, 0xc5, 0xb9, 0x18, 0x37, 0x7f, 0xfc, 0xe3, 0xaf, 0xdf, 0xe4, 0x32, 0x52,
	0xc4, 0xdf, 0x20, 0xfa, 0x0e, 0xd4, 0xcc, 0xa1, 0x46, 0x0f, 0x32, 0x5f, 0x2e, 0xef, 0x1d, 0xfd,
	0xdd, 0x75, 0xe6, 0x84, 0x5c, 0x13, 0xe4, 0xd0, 0x8e, 0xc9, 0xf7, 0xa5, 0x16, 0xe7, 0xcf, 0x9c,
	0x80, 0x1c, 0xff, 0xf2, 0x32, 0xc8, 0xf1, 0xaf, 0x38, 0x38, 0x73, 0x7e, 0x63, 0xc1, 0xff, 0x12,
	0xd4, 0xcc, 0x04, 0xe7, 0xf8, 0x97, 0x8f, 0x4e, 0x8e, 0x7f, 0xc5, 0xe0, 0xcf, 0x8b, 0xd3, 0x4a,
	0x8a, 0x83, 0x01, 0x16, 0xd3, 0x80, 0xee, 0x67, 0xd7, 0xc0, 0xe5, 0xa9, 0xd7, 0x1f, 0xac, 0xb1,
	0x26, 0xcc, 0x77, 0x05, 0xb3, 0x66, 0xa8, 0x82, 0xd9, 0xa2, 0x1c, 0xb1, 0x2f, 0xb5, 0xbe, 0x98,
	0xfe, 0xda, 0xd9, 0x43, 0x4a, 0xbb, 0xf0, 0x91, 0xf9, 0x61, 0x4b, 0x92, 0xa3, 0xf7, 0x41, 0x39,
	0xe4, 0x34, 0xa8, 0x31, 0x62, 0x2c, 0xa4, 0xfb, 0x96, 0xe5, 0x7a, 0x6c, 0x34, 0x3b, 0x33, 0x87,
	0xc1, 0xd4, 0x9a, 0x78, 0x78, 0xfa, 0xa8, 0xbd, 0x6b, 0x09, 0xc4, 0xb7, 0xbb, 0xeb, 0x2c, 0x16,
	0x25, 0xd1, 0x39, 0x89, 0xac, 0x70, 0xec, 0xc6, 0xbf, 0xe6, 0x56, 0xfa, 0x83, 0x7f, 0x56, 0x12,
	0x8a, 0xdd, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xd7, 0xf3, 0x43, 0x15, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataServiceClient interface {
	// Get the list of all data for the logged in user, or a specific datum if
	// specified.
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
	// Update the specified datum with new data.
	UpdateDatum(ctx context.Context, in *UpdateDatumRequest, opts ...grpc.CallOption) (*UpdateDatumResponse, error)
	// Create a new datum.
	CreateDatum(ctx context.Context, in *CreateDatumRequest, opts ...grpc.CallOption) (*CreateDatumResponse, error)
	// Delete the specified datum.
	DeleteDatum(ctx context.Context, in *DeleteDatumRequest, opts ...grpc.CallOption) (*DeleteDatumResponse, error)
	// Share a datum with another user by granting them new permission(s) on it.
	ShareDatum(ctx context.Context, in *ShareDatumRequest, opts ...grpc.CallOption) (*ShareDatumResponse, error)
}

type dataServiceClient struct {
	cc *grpc.ClientConn
}

func NewDataServiceClient(cc *grpc.ClientConn) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, "/kript.api.DataService/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) UpdateDatum(ctx context.Context, in *UpdateDatumRequest, opts ...grpc.CallOption) (*UpdateDatumResponse, error) {
	out := new(UpdateDatumResponse)
	err := c.cc.Invoke(ctx, "/kript.api.DataService/UpdateDatum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) CreateDatum(ctx context.Context, in *CreateDatumRequest, opts ...grpc.CallOption) (*CreateDatumResponse, error) {
	out := new(CreateDatumResponse)
	err := c.cc.Invoke(ctx, "/kript.api.DataService/CreateDatum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) DeleteDatum(ctx context.Context, in *DeleteDatumRequest, opts ...grpc.CallOption) (*DeleteDatumResponse, error) {
	out := new(DeleteDatumResponse)
	err := c.cc.Invoke(ctx, "/kript.api.DataService/DeleteDatum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) ShareDatum(ctx context.Context, in *ShareDatumRequest, opts ...grpc.CallOption) (*ShareDatumResponse, error) {
	out := new(ShareDatumResponse)
	err := c.cc.Invoke(ctx, "/kript.api.DataService/ShareDatum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
type DataServiceServer interface {
	// Get the list of all data for the logged in user, or a specific datum if
	// specified.
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	// Update the specified datum with new data.
	UpdateDatum(context.Context, *UpdateDatumRequest) (*UpdateDatumResponse, error)
	// Create a new datum.
	CreateDatum(context.Context, *CreateDatumRequest) (*CreateDatumResponse, error)
	// Delete the specified datum.
	DeleteDatum(context.Context, *DeleteDatumRequest) (*DeleteDatumResponse, error)
	// Share a datum with another user by granting them new permission(s) on it.
	ShareDatum(context.Context, *ShareDatumRequest) (*ShareDatumResponse, error)
}

// UnimplementedDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataServiceServer struct {
}

func (*UnimplementedDataServiceServer) GetData(ctx context.Context, req *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (*UnimplementedDataServiceServer) UpdateDatum(ctx context.Context, req *UpdateDatumRequest) (*UpdateDatumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDatum not implemented")
}
func (*UnimplementedDataServiceServer) CreateDatum(ctx context.Context, req *CreateDatumRequest) (*CreateDatumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDatum not implemented")
}
func (*UnimplementedDataServiceServer) DeleteDatum(ctx context.Context, req *DeleteDatumRequest) (*DeleteDatumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDatum not implemented")
}
func (*UnimplementedDataServiceServer) ShareDatum(ctx context.Context, req *ShareDatumRequest) (*ShareDatumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareDatum not implemented")
}

func RegisterDataServiceServer(s *grpc.Server, srv DataServiceServer) {
	s.RegisterService(&_DataService_serviceDesc, srv)
}

func _DataService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kript.api.DataService/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_UpdateDatum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDatumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).UpdateDatum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kript.api.DataService/UpdateDatum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).UpdateDatum(ctx, req.(*UpdateDatumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_CreateDatum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).CreateDatum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kript.api.DataService/CreateDatum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).CreateDatum(ctx, req.(*CreateDatumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_DeleteDatum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).DeleteDatum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kript.api.DataService/DeleteDatum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).DeleteDatum(ctx, req.(*DeleteDatumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_ShareDatum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareDatumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).ShareDatum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kript.api.DataService/ShareDatum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).ShareDatum(ctx, req.(*ShareDatumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kript.api.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _DataService_GetData_Handler,
		},
		{
			MethodName: "UpdateDatum",
			Handler:    _DataService_UpdateDatum_Handler,
		},
		{
			MethodName: "CreateDatum",
			Handler:    _DataService_CreateDatum_Handler,
		},
		{
			MethodName: "DeleteDatum",
			Handler:    _DataService_DeleteDatum_Handler,
		},
		{
			MethodName: "ShareDatum",
			Handler:    _DataService_ShareDatum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kript/api/data.proto",
}
