// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kript/api/universal.proto

package api

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// An enumeration of different password hashing algorithms.
type HashAlgorithm int32

const (
	HashAlgorithm_UNKNOWN_HASH_ALGORITHM HashAlgorithm = 0
	// Hash the utf-8 encoded password and utf-8 encoded salt using bcrypt with a cost of 10.
	HashAlgorithm_BCRYPT HashAlgorithm = 1
	// Hash the utf-8 encoded password and utf-8 encoded salt using scrypt with N=16384, r=8, p=1, and derived key length = 256 bits
	HashAlgorithm_SCRYPT HashAlgorithm = 2
	// Hash the utf-8 encoded password and utf-8 encoded salt using PBKDF2 with SHA512, 20000 iterations, and a derived key length of 256 bits
	HashAlgorithm_PBKDF2_SHA_512 HashAlgorithm = 3
	// Hash the utf-8 encoded password and utf-8 encoded salt using Argon2id, with t=75, m=1024, p=1, T=32 (derived key length of 256 bits).
	HashAlgorithm_ARGON2 HashAlgorithm = 4
)

var HashAlgorithm_name = map[int32]string{
	0: "UNKNOWN_HASH_ALGORITHM",
	1: "BCRYPT",
	2: "SCRYPT",
	3: "PBKDF2_SHA_512",
	4: "ARGON2",
}

var HashAlgorithm_value = map[string]int32{
	"UNKNOWN_HASH_ALGORITHM": 0,
	"BCRYPT":                 1,
	"SCRYPT":                 2,
	"PBKDF2_SHA_512":         3,
	"ARGON2":                 4,
}

func (x HashAlgorithm) String() string {
	return proto.EnumName(HashAlgorithm_name, int32(x))
}

func (HashAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f55c2955aa4afcfe, []int{0}
}

// An enumeration of different symmetric encryption algorithms.
type SEncryptionAlgorithm int32

const (
	SEncryptionAlgorithm_UNKNOWN_S_ENCRYPTION_ALGORITHM SEncryptionAlgorithm = 0
	// Encrypt using AES-256 with a given key and initialization vector, using CBC and PKCS7 padding. If the key is longer than 256 bits, it is truncated to 256. If it is shorter, it is zero-padded.
	SEncryptionAlgorithm_AES_256_CBC SEncryptionAlgorithm = 1
	// Encrypt using AES-256 with a given key and initialization vector, using GCM. If the key is longer than 256 bits, it is truncated to 256. If it is shorter, it is zero-padded.
	SEncryptionAlgorithm_AES_256_GCM SEncryptionAlgorithm = 2
)

var SEncryptionAlgorithm_name = map[int32]string{
	0: "UNKNOWN_S_ENCRYPTION_ALGORITHM",
	1: "AES_256_CBC",
	2: "AES_256_GCM",
}

var SEncryptionAlgorithm_value = map[string]int32{
	"UNKNOWN_S_ENCRYPTION_ALGORITHM": 0,
	"AES_256_CBC":                    1,
	"AES_256_GCM":                    2,
}

func (x SEncryptionAlgorithm) String() string {
	return proto.EnumName(SEncryptionAlgorithm_name, int32(x))
}

func (SEncryptionAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f55c2955aa4afcfe, []int{1}
}

// An enumeration of different asymmetric encryption algorithms.
type AEncryptionAlgorithm int32

const (
	AEncryptionAlgorithm_UNKNOWN_A_ENCRYPTION_ALGORITHM AEncryptionAlgorithm = 0
	// Encrypt/Decrypt using RSA, using OAEP padding.
	AEncryptionAlgorithm_RSA AEncryptionAlgorithm = 1
)

var AEncryptionAlgorithm_name = map[int32]string{
	0: "UNKNOWN_A_ENCRYPTION_ALGORITHM",
	1: "RSA",
}

var AEncryptionAlgorithm_value = map[string]int32{
	"UNKNOWN_A_ENCRYPTION_ALGORITHM": 0,
	"RSA":                            1,
}

func (x AEncryptionAlgorithm) String() string {
	return proto.EnumName(AEncryptionAlgorithm_name, int32(x))
}

func (AEncryptionAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f55c2955aa4afcfe, []int{2}
}

type AccessToken struct {
	Jwt                  *JWT     `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_f55c2955aa4afcfe, []int{0}
}
func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetJwt() *JWT {
	if m != nil {
		return m.Jwt
	}
	return nil
}

// A representation of a JSON Web Token.
type JWT struct {
	// The Base 64 encoded JWT.
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWT) Reset()         { *m = JWT{} }
func (m *JWT) String() string { return proto.CompactTextString(m) }
func (*JWT) ProtoMessage()    {}
func (*JWT) Descriptor() ([]byte, []int) {
	return fileDescriptor_f55c2955aa4afcfe, []int{1}
}
func (m *JWT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWT.Unmarshal(m, b)
}
func (m *JWT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWT.Marshal(b, m, deterministic)
}
func (m *JWT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWT.Merge(m, src)
}
func (m *JWT) XXX_Size() int {
	return xxx_messageInfo_JWT.Size(m)
}
func (m *JWT) XXX_DiscardUnknown() {
	xxx_messageInfo_JWT.DiscardUnknown(m)
}

var xxx_messageInfo_JWT proto.InternalMessageInfo

func (m *JWT) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("kript.api.HashAlgorithm", HashAlgorithm_name, HashAlgorithm_value)
	proto.RegisterEnum("kript.api.SEncryptionAlgorithm", SEncryptionAlgorithm_name, SEncryptionAlgorithm_value)
	proto.RegisterEnum("kript.api.AEncryptionAlgorithm", AEncryptionAlgorithm_name, AEncryptionAlgorithm_value)
	proto.RegisterType((*AccessToken)(nil), "kript.api.AccessToken")
	proto.RegisterType((*JWT)(nil), "kript.api.JWT")
}

func init() { proto.RegisterFile("kript/api/universal.proto", fileDescriptor_f55c2955aa4afcfe) }

var fileDescriptor_f55c2955aa4afcfe = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xcf, 0x6b, 0xea, 0x40,
	0x18, 0x7c, 0x31, 0xef, 0xf9, 0xf0, 0x93, 0xe7, 0x5b, 0x16, 0x29, 0xfd, 0x01, 0x45, 0x3c, 0x15,
	0x0f, 0x59, 0x1a, 0xb1, 0xd0, 0xe3, 0x26, 0xb5, 0x46, 0xad, 0x89, 0x64, 0x53, 0xa4, 0xa5, 0xb0,
	0xc4, 0x10, 0x74, 0xab, 0x26, 0x61, 0xb3, 0x5a, 0xfa, 0xdf, 0x97, 0x44, 0x6a, 0xdb, 0x43, 0xe9,
	0x6d, 0xbe, 0x99, 0xf9, 0x66, 0x0e, 0x03, 0x27, 0x2b, 0x29, 0x32, 0x45, 0xc2, 0x4c, 0x90, 0x6d,
	0x22, 0x76, 0xb1, 0xcc, 0xc3, 0xb5, 0x91, 0xc9, 0x54, 0xa5, 0xb8, 0x56, 0x4a, 0x46, 0x98, 0x89,
	0x36, 0x81, 0x3a, 0x8d, 0xa2, 0x38, 0xcf, 0x83, 0x74, 0x15, 0x27, 0xb8, 0x05, 0xfa, 0xf3, 0x8b,
	0x3a, 0xd6, 0x5a, 0xda, 0x45, 0xdd, 0x6c, 0x18, 0x07, 0x9f, 0x31, 0x9a, 0x05, 0x7e, 0x21, 0xb5,
	0xcf, 0x40, 0x1f, 0xcd, 0x02, 0xdc, 0x84, 0x3f, 0xaa, 0xf8, 0x28, 0xad, 0x35, 0x7f, 0x7f, 0x74,
	0x22, 0xf8, 0xe7, 0x84, 0xf9, 0x92, 0xae, 0x17, 0xa9, 0x14, 0x6a, 0xb9, 0xc1, 0xa7, 0x70, 0x74,
	0xef, 0x8e, 0x5d, 0x6f, 0xe6, 0x72, 0x87, 0x32, 0x87, 0xd3, 0xbb, 0x81, 0xe7, 0x0f, 0x03, 0x67,
	0x82, 0x7e, 0x61, 0x80, 0xaa, 0x65, 0xfb, 0x0f, 0xd3, 0x00, 0x69, 0x05, 0x66, 0x7b, 0x5c, 0xc1,
	0x18, 0x1a, 0x53, 0x6b, 0x7c, 0x73, 0x6b, 0x72, 0xe6, 0x50, 0xde, 0xbb, 0x34, 0x91, 0x5e, 0xe8,
	0xd4, 0x1f, 0x78, 0xae, 0x89, 0x7e, 0x77, 0x9e, 0xa0, 0xc9, 0xfa, 0x49, 0x24, 0x5f, 0x33, 0x25,
	0xd2, 0xe4, 0xa3, 0xab, 0x0d, 0xe7, 0xef, 0x5d, 0x8c, 0xf7, 0xdd, 0x32, 0x6e, 0xe8, 0xb9, 0x5f,
	0x3a, 0xff, 0x43, 0x9d, 0xf6, 0x19, 0x37, 0x7b, 0x57, 0xdc, 0xb6, 0x6c, 0xa4, 0x7d, 0x26, 0x06,
	0xf6, 0x04, 0x55, 0x3a, 0x36, 0x34, 0xe9, 0x0f, 0xe9, 0xf4, 0xbb, 0xf4, 0xbf, 0xa0, 0xfb, 0x8c,
	0x22, 0xcd, 0xea, 0x3d, 0x76, 0x17, 0x42, 0x2d, 0xb7, 0x73, 0x23, 0x4a, 0x37, 0x64, 0x2d, 0xc2,
	0xcd, 0xb5, 0xd9, 0x25, 0xe3, 0x72, 0x90, 0x3c, 0x96, 0xbb, 0x58, 0x92, 0x6c, 0xb5, 0x20, 0xe5,
	0x1a, 0xe4, 0xb0, 0xd3, 0xbc, 0x5a, 0x12, 0xdd, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x22,
	0x47, 0x95, 0xbb, 0x01, 0x00, 0x00,
}
