FROM golang:1.14 AS build
WORKDIR '/app'
COPY . .
RUN CGO_ENABLED=0 go build -o /app/bin/kript-grpc github.com/liam923/Kript/server/cmd/kript-grpc

FROM alpine:latest as certs
RUN apk --update add ca-certificates

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=build /app/bin /
ENTRYPOINT ["/kript-grpc"]