FROM golang:1.14 AS build
WORKDIR '/app'
COPY . .
RUN CGO_ENABLED=0 go build -o /app/bin/api cmd/api/main.go

FROM scratch
COPY --from=build /app/bin /
ENV REST_PORT 10000
ENV GRPC_PORT 11000
EXPOSE $REST_PORT $GRPC_PORT
CMD ["/api"]