FROM golang:1.14 AS build
WORKDIR '/app'
COPY . .
RUN CGO_ENABLED=0 go build -o /app/bin/kript-data github.com/liam923/Kript/server/cmd/kript-data

FROM alpine:latest as certs
RUN apk --update add ca-certificates

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=build /app/bin /
COPY secret /secret
ENV GOOGLE_APPLICATION_CREDENTIALS secret/credentials.json
ENTRYPOINT ["/kript-data", "-public-jwt=/secret/jwt.public.pem"]