#!/usr/bin/env bash
set -e

# The purpose of this script is to deploy the docker images to Cloud Run when being built on the master branch.

if [ "$BRANCH" = "master" ]; then
  echo "master branch detected. deploying commit ${SHORT_SHA} for project ${PROJECT_ID}"

  echo "deploying account service: gcr.io/${PROJECT_ID}/kript-account:${SHORT_SHA}"
  gcloud run deploy account --image "gcr.io/${PROJECT_ID}/kript-account:${SHORT_SHA}" --region 'us-east4' --platform managed

  echo "deploying data service: gcr.io/${PROJECT_ID}/kript-data:${SHORT_SHA}"
  gcloud run deploy data --image "gcr.io/${PROJECT_ID}/kript-data:${SHORT_SHA}" --region 'us-east4' --platform managed

  echo "deploying gateway service: gcr.io/${PROJECT_ID}/kript-gateway:${SHORT_SHA}"
  gcloud run deploy gateway --image "gcr.io/${PROJECT_ID}/kript-gateway:${SHORT_SHA}" --region 'us-east4' --platform managed

  echo "deploying grpc service: gcr.io/${PROJECT_ID}/kript-grpc:${SHORT_SHA}"
  gcloud run deploy grpc --image "gcr.io/${PROJECT_ID}/kript-grpc:${SHORT_SHA}" --region 'us-east4' --platform managed
else
  echo "${BRANCH} branch detected; not deploying"
fi