#!/usr/bin/env bash
set -e

# The purpose of this script is to fetch secret files from the cloud Secret Manager.

# Change directory to /server
cd "${0%/*}"
cd ..

mkdir -p secret

gcloud secrets versions access latest --secret=google-application-credentials --format='get(payload.data)' | tr '_-' '/+' | base64 -d > secret/credentials.json
gcloud secrets versions access latest --secret=jwt-private --format='get(payload.data)' | tr '_-' '/+' | base64 -d > secret/jwt.private.pem
gcloud secrets versions access latest --secret=jwt-public --format='get(payload.data)' | tr '_-' '/+' | base64 -d > secret/jwt.public.pem
gcloud secrets versions access latest --secret=sendgrid-api-key --format='get(payload.data)' | tr '_-' '/+' | base64 -d > secret/sendgrid-api-key